export const routes = {
    HOME: '/',
    DASHBOARD: '/dashboard',
    ROOMS: '/rooms',
    ID: ':id',
    ROOM_TYPE: '/room-type',
    BOOKINGS: '/bookings',
    CUSTOMERS: '/customers',
    ADMIN: '/admin',
    REVENUE: '/revenue',
    BILLINGS: '/billings',
    FLOOR: '/floor',
    COMPLAINT: '/complaint',
    MAINTENANCE: '/maintenance',
    LOGIN: '/login',
    PROFILE: '/profile',
    EMPLOYEE: '/employee',
    SALARY:'/salary',
    EXPENSE:'/expense',
    CALENDAR_BOOKING: '/calendar-booking',
}
