const columns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "NAME", uid: "name", sortable: true },
    { name: "FIRST NAME", uid: "firstName", sortable: true },
    { name: "LAST NAME", uid: "lastName", sortable: true },
    { name: "ADDRESS", uid: "address" },
    { name: "DATE OF BIRTH", uid: "dateOfBirth", sortable: true },
    { name: "CONTACT", uid: "contact" },
    { name: "EMAIL", uid: "email", sortable: true },
    { name: "GENDER", uid: "gender" },
    { name: "COMPANY", uid: "company" },
    { name: "CREATED AT", uid: "createdAt", sortable: true },
    { name: "UPDATED AT", uid: "updatedAt", sortable: true },
    {name: "ACTIONS", uid: "actions"},
  ];
  
  const genderOptions = [
    { name: "Male", uid: "male" },
    { name: "Female", uid: "female" },
    { name: "Other", uid: "other" },
  ];
  
  const customers = [
    {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      address: "123 Main Street, Springfield",
      dateOfBirth: "1990-05-20",
      contact: "1234567890",
      email: "john.doe@example.com",
      gender: "Male",
      company: "ABC Corp",
      createdAt: "2024-01-15",
      updatedAt: "2024-02-10",
    },
    {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      address: "456 Oak Avenue, Metropolis",
      dateOfBirth: "1985-08-15",
      contact: "0987654321",
      email: "jane.smith@example.com",
      gender: "Female",
      company: "XYZ Inc",
      createdAt: "2024-01-18",
      updatedAt: "2024-02-12",
    },
    {
      id: 3,
      firstName: "Michael",
      lastName: "Johnson",
      address: "", // replaced null with an empty string
      dateOfBirth: "1993-11-12",
      contact: "5551234567",
      email: "michael.j@example.com",
      gender: "Male",
      company: "", // replaced null with an empty string
      createdAt: "2024-01-20",
      updatedAt: "2024-02-13",
    },
    {
      id: 4,
      firstName: "Emily",
      lastName: "Davis",
      address: "789 Pine Road, Gotham",
      dateOfBirth: "1997-03-25",
      contact: "6669876543",
      email: "emily.davis@example.com",
      gender: "Female",
      company: "Tech Solutions",
      createdAt: "2024-01-25",
      updatedAt: "2024-02-14",
    },
    {
      id: 5,
      firstName: "Chris",
      lastName: "Brown",
      address: "321 Elm Street, Star City",
      dateOfBirth: "2000-09-08",
      contact: "4441122334",
      email: "chris.brown@example.com",
      gender: "Other",
      company: "", // replaced null with an empty string
      createdAt: "2024-02-01",
      updatedAt: "2024-02-15",
    },
    {
      id: 6,
      firstName: "Sarah",
      lastName: "Lee",
      address: "12 Maple Drive, Central City",
      dateOfBirth: "1992-07-14",
      contact: "7778899000",
      email: "sarah.lee@example.com",
      gender: "Female",
      company: "MediaHouse",
      createdAt: "2024-01-12",
      updatedAt: "2024-02-05",
    },
    {
      id: 7,
      firstName: "David",
      lastName: "Martinez",
      address: "34 Cedar Lane, Hill Valley",
      dateOfBirth: "1988-02-10",
      contact: "1112233445",
      email: "david.martinez@example.com",
      gender: "Male",
      company: "Construction Pro",
      createdAt: "2024-01-14",
      updatedAt: "2024-02-06",
    },
    {
      id: 8,
      firstName: "Laura",
      lastName: "Wilson",
      address: "", // replaced null with an empty string
      dateOfBirth: "1995-12-01",
      contact: "2223344556",
      email: "laura.wilson@example.com",
      gender: "Female",
      company: "", // replaced null with an empty string
      createdAt: "2024-01-16",
      updatedAt: "2024-02-08",
    },
    {
      id: 9,
      firstName: "Daniel",
      lastName: "Garcia",
      address: "567 Birch Street, Coast City",
      dateOfBirth: "1991-04-18",
      contact: "3334455667",
      email: "daniel.garcia@example.com",
      gender: "Male",
      company: "AutoFix",
      createdAt: "2024-01-19",
      updatedAt: "2024-02-09",
    },
    {
      id: 10,
      firstName: "Megan",
      lastName: "Young",
      address: "78 Aspen Way, National City",
      dateOfBirth: "1998-06-09",
      contact: "8885566778",
      email: "megan.young@example.com",
      gender: "Female",
      company: "HealthFirst",
      createdAt: "2024-01-22",
      updatedAt: "2024-02-11",
    },
    {
      id: 11,
      firstName: "Joshua",
      lastName: "Anderson",
      address: "90 Walnut Lane, Keystone",
      dateOfBirth: "1984-09-05",
      contact: "4446677889",
      email: "joshua.anderson@example.com",
      gender: "Male",
      company: "", // replaced null with an empty string
      createdAt: "2024-01-23",
      updatedAt: "2024-02-12",
    },
    {
      id: 12,
      firstName: "Hannah",
      lastName: "Clark",
      address: "21 Olive Road, Emerald City",
      dateOfBirth: "1990-11-23",
      contact: "9997788990",
      email: "hannah.clark@example.com",
      gender: "Female",
      company: "EcoWorld",
      createdAt: "2024-01-26",
      updatedAt: "2024-02-13",
    },
    {
      id: 13,
      firstName: "Samuel",
      lastName: "Miller",
      address: "43 Cypress Street, Fawcett City",
      dateOfBirth: "1987-01-15",
      contact: "5558899001",
      email: "samuel.miller@example.com",
      gender: "Male",
      company: "MillerTech",
      createdAt: "2024-01-28",
      updatedAt: "2024-02-16",
    },
    {
      id: 14,
      firstName: "Olivia",
      lastName: "Rodriguez",
      address: "", // replaced null with an empty string
      dateOfBirth: "1994-03-12",
      contact: "3331122334",
      email: "olivia.rodriguez@example.com",
      gender: "Female",
      company: "Rodriguez Designs",
      createdAt: "2024-01-30",
      updatedAt: "2024-02-17",
    },
    {
      id: 15,
      firstName: "William",
      lastName: "Walker",
      address: "56 Chestnut Street, Smallville",
      dateOfBirth: "1986-10-20",
      contact: "7776677888",
      email: "william.walker@example.com",
      gender: "Male",
      company: "SafeNet",
      createdAt: "2024-02-02",
      updatedAt: "2024-02-18",
    },
    {
      id: 16,
      firstName: "Sophia",
      lastName: "Taylor",
      address: "98 Birchwood Ave, Starlight City",
      dateOfBirth: "1999-12-25",
      contact: "1115566779",
      email: "sophia.taylor@example.com",
      gender: "Female",
      company: "", // replaced null with an empty string
      createdAt: "2024-02-05",
      updatedAt: "2024-02-19",
    },
    {
      id: 17,
      firstName: "Ryan",
      lastName: "Perez",
      address: "75 Palm Lane, Paradise Island",
      dateOfBirth: "1992-05-11",
      contact: "2226677889",
      email: "ryan.perez@example.com",
      gender: "Male",
      company: "Perez Builders",
      createdAt: "2024-02-08",
      updatedAt: "2024-02-20",
    },
    {
      id: 18,
      firstName: "Emma",
      lastName: "White",
      address: "14 Seaside Blvd, Bay City",
      dateOfBirth: "1996-02-17",
      contact: "5557788992",
      email: "emma.white@example.com",
      gender: "Female",
      company: "White Events",
      createdAt: "2024-02-10",
      updatedAt: "2024-02-21",
    },
    {
      id: 19,
      firstName: "James",
      lastName: "Harris",
      address: "65 Hilltop Lane, Riverdale",
      dateOfBirth: "1983-08-21",
      contact: "9996677881",
      email: "james.harris@example.com",
      gender: "Male",
      company: "", // replaced null with an empty string
      createdAt: "2024-02-12",
      updatedAt: "2024-02-22",
    },
    {
      id: 20,
      firstName: "Isabella",
      lastName: "Martinez",
      address: "32 Ocean Drive, Beach City",
      dateOfBirth: "2001-07-03",
      contact: "6667788993",
      email: "isabella.martinez@example.com",
      gender: "Female",
      company: "Martinez Enterprises",
      createdAt: "2024-02-14",
      updatedAt: "2024-02-23",
    },
  ];
  
  
  export { columns, customers, genderOptions };
  
  